export const productName = 'The GDPR Checklist'
export const url = 'http://gdprchecklist.io'
export const description = 'Achieving GDPR Compliance shouldn\'t feel like a struggle. This is a basic checklist you can use to harden your GDPR compliancy. '
export const keywords = 'GDPR, Privacy, Data, Europe, Compliance, GDPR Checklist, GDPR Compliance, Security, General Data Protection Regulation, Data Processor, Data Controller'
export const title = 'The GDPR Checklist - Your GDPR compliance checklist'
export const twitter = '@privacyradius'
export const imagePreview = url + '/preview.png'